---
- name: Ensure Pip is installed.
  become: true
  package:
    name: "python3-pip"
    state: present

- name: Install docker libraries
  pip:
    name:
      - docker
      - docker-compose
    state: present

- name: Delete existing docker-compose version.
  file:
    path: "{{ docker_compose_path }}"
    state: absent

- name: Install Docker Compose.
  get_url:
    url: "{{ docker_compose_url }}"
    dest: "{{ docker_compose_path }}"
    mode: 0755
