---

- include_tasks: prepare-Ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

- name: Install Docker via ansible package manager
  ansible.builtin.package:
    name: "docker-ce"
    state: present

- name: Ensure /etc/docker/ directory exists.
  file:
    path: /etc/docker
    state: directory
    mode: 0755

- name: Ensure Docker is started and enabled at boot.
  service:
    name: docker
    state: "{{ docker_service_state }}"
    enabled: "{{ docker_service_enabled }}"

- name: Ensure user is added to the docker group.
  user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: true
  become: yes

- include_tasks: install-compose.yml
  when: docker_compose_install | bool 