apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "clock-app.fullname" . }}
  labels:
    {{- include "clock-app.labels" . | nindent 4 }}
spec:
  podManagementPolicy: Parallel
  serviceName: {{ include "clock-app.fullname" . }}
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "clock-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "clock-app.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "clock-app.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          env:
            - name: TRUTH_ABOUT_DEVOPS
              valueFrom:
                secretKeyRef:
                  name: devops-secret
                  key: devops
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: config-volume
              mountPath: {{ .Values.image.mountDir }}
            - name: logs
              mountPath: {{ .Values.image.logsDir }}
      volumes:
        - name: config-volume
          configMap:
            name: sample-config
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  volumeClaimTemplates:
  - metadata:
      name: logs
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
