server:
  http_listen_port: 9080

client:
  url: http://loki:3100/loki/api/v1/push

scrape_configs:
- job_name: docker
  static_configs:
  - targets:
    - localhost
    labels:
      __path__: /var/lib/docker/containers/*/*log
      job: containers

  pipeline_stages:
    - json:
        expressions:
          stream: stream
          attrs: attrs
          tag: attrs.tag
          time: attrs.time
    - timestamp:
        source: time
        format: RFC3339Nano
    - regex:
        expression: ^(?P<image_name>([^|]+))\|(?P<container_name>([^|]+))$
        source: tag
    - labels:
        image_name:
        container_name: