version: "3.9"
services:

  # The app itself 
  clock:
    image: mexator/clock
    ports: 
      - "80:5000"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
        tag:
          "{{.ImageName}}|{{.Name}}"
    networks:
      - monitoring.network
    deploy:
      resources:
        limits:
          memory: "64M"

  
  # Log gathering agent
  promtail:
    image: grafana/promtail:${LOKI_VERSION}
    command: -config.file=/etc/promtail/config.yml
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers
      - ./promtail/config.yml:/etc/promtail/config.yml
    expose: 
      - 9080
    ports: 
      - "9080:9080"
    networks:
      - monitoring.network
    deploy:
      resources:
        limits:
          memory: "512M"

  # Log indexer
  loki:
    image: grafana/loki:${LOKI_VERSION}
    command: -config.file=/etc/loki/local-config.yaml
    expose:
      - 3100
    ports: 
      - "3100:3100"
    networks:
      - monitoring.network
    deploy:
      resources:
        limits:
          memory: "512M"
  
  # Metrics collector
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    command:
      - "--config.file=/etc/prometheus/config.yml"
    volumes:
      - ./prometheus/config.yml:/etc/prometheus/config.yml
    networks:
      - monitoring.network
    deploy:
      resources:
        limits:
          memory: "512M"

  # Visualiser dashboard
  grafana:
    image: grafana/grafana:latest
    expose: 
      - 3000
    ports: 
      - "3000:3000"
    networks:
      - monitoring.network
    deploy:
      resources:
        limits:
          memory: "512M"

networks:
  monitoring.network:
    ipam:
      driver: default