---

# Docker repo URL.
docker_repo_url: https://download.docker.com/linux
# Location of gpg key
docker_apt_gpg_key: "{{ docker_repo_url }}/ubuntu/gpg"
# Whether to stop execution if gpg keys does not match
docker_apt_ignore_key_error: true

docker_apt_arch: amd64
docker_apt_repository: "deb [arch={{ docker_apt_arch }}] {{ docker_repo_url }}/ubuntu {{ ansible_distribution_release }} stable"

# variables that indicate desired state of Docker daemon
docker_service_state: started
docker_service_enabled: true