name: "Build and push Docker image"

on:
  push:
    branches: 
    - master

jobs:
  # todo: сбилдить имедж с зависимостями для теста и для запуска?
  # затем запушить
  # затем сбилдить имедж с сервером
  # затем запушить