name: "Build and push Docker image"

on:
  push:
    branches: 
    - master
    - dev
    tags: v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        id: buildx

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Docker log in
        uses: docker/login-action@v1.10.0
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWD}}

      - uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-git-tag

      - name: Form docker tag
        id: build-tag 
        run: | 
          TAG_PATTERN="^refs/tags/.+"
          git_tag=${{ steps.get-git-tag.outputs.tag }}
          if [["$GITHUB_REF"=~TAG_PATTERN]]; then
            tag=mexator/clock:$git_tag
          else
            tag=mexator/clock:git-$git_tag
          fi
          echo "TAG=$tag" >> $GITHUB_ENV
      
      - name: Build & push image
        uses: docker/build-push-action@v2
        with:
          context: app_python
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{env.TAG}}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      - name: Cache hack
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache