name: "Build and push Docker image"

on:
  push:
    branches: 
    - master
    tags: v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Docker log in
        uses: docker/login-action@v1.10.0
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWD}}

      - uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-git-tag

      - name: Form docker tag
        id: build-tag 
        run: | 
          TAG_PATTERN="^refs/tags/.+"
          git_tag=${{ steps.get-git-tag.outputs.tag }}
          if [["$GITHUB_REF"=~TAG_PATTERN]]; then
            tag=mexator/clock:$git_tag
          else
            tag=mexator/clock:git-$git_tag
          fi
          echo "TAG=$tag" >> $GITHUB_ENV

      - name: Build docker image
        run: |
          cd app_python
          docker build -t ${{env.TAG}} . 

      - name: Push docker image
        run: |
          docker push ${{env.TAG}}
